source 'https://rubygems.org'

gem 'rails', '3.2.11'
gem 'mysql2'
group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'devise'
gem 'omniauth'
gem 'oauth2'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'omniauth-openid'
gem 'omniauth-google-oauth2'
require 'digest/md5'
require 'securerandom'
gem 'kaminari'
gem 'rails_autolink'
gem 'simple_form'
gem 'client_side_validations'
gem 'client_side_validations-simple_form'
gem 'mailcatcher'
gem 'profanity_filter'
gem 'less-rails'
gem 'twitter-bootstrap-rails'
gem 'yaml_db'